module Fable.Helpers.OfficeUIFabricReact.IconName

open System
open Fable.Core
open Fable.Core.JsInterop
open Fable.Import
open Fable.Import.Browser
open Fable.Helpers.React
open Fable.Helpers.React.Props

[<StringEnum>]
type IconName =
    | [<CompiledName("CustomIcon")>] CustomIcon
    | [<CompiledName("None")>] None
    | [<CompiledName("AADLogo")>] AADLogo
    | [<CompiledName("Accept")>] Accept
    | [<CompiledName("AccessLogo")>] AccessLogo
    | [<CompiledName("AccessLogoFill")>] AccessLogoFill
    | [<CompiledName("Accounts")>] Accounts
    | [<CompiledName("ActivityFeed")>] ActivityFeed
    | [<CompiledName("Add")>] Add
    | [<CompiledName("AddEvent")>] AddEvent
    | [<CompiledName("AddFavorite")>] AddFavorite
    | [<CompiledName("AddFavoriteFill")>] AddFavoriteFill
    | [<CompiledName("AddFriend")>] AddFriend
    | [<CompiledName("AddGroup")>] AddGroup
    | [<CompiledName("AddOnlineMeeting")>] AddOnlineMeeting
    | [<CompiledName("AddPhone")>] AddPhone
    | [<CompiledName("AddTo")>] AddTo
    | [<CompiledName("Admin")>] Admin
    | [<CompiledName("AdminALogo")>] AdminALogo
    | [<CompiledName("AdminCLogo")>] AdminCLogo
    | [<CompiledName("AdminDLogo")>] AdminDLogo
    | [<CompiledName("AdminELogo")>] AdminELogo
    | [<CompiledName("AdminLLogo")>] AdminLLogo
    | [<CompiledName("AdminMLogo")>] AdminMLogo
    | [<CompiledName("AdminOLogo")>] AdminOLogo
    | [<CompiledName("AdminPLogo")>] AdminPLogo
    | [<CompiledName("AdminSLogo")>] AdminSLogo
    | [<CompiledName("AdminYLogo")>] AdminYLogo
    | [<CompiledName("Airplane")>] Airplane
    | [<CompiledName("AirTickets")>] AirTickets
    | [<CompiledName("AlarmClock")>] AlarmClock
    | [<CompiledName("Album")>] Album
    | [<CompiledName("AlbumRemove")>] AlbumRemove
    | [<CompiledName("AlignCenter")>] AlignCenter
    | [<CompiledName("AlignLeft")>] AlignLeft
    | [<CompiledName("AlignRight")>] AlignRight
    | [<CompiledName("AnalyticsLogo")>] AnalyticsLogo
    | [<CompiledName("AnalyticsQuery")>] AnalyticsQuery
    | [<CompiledName("AnalyticsReport")>] AnalyticsReport
    | [<CompiledName("AndroidLogo")>] AndroidLogo
    | [<CompiledName("Annotation")>] Annotation
    | [<CompiledName("AppIconDefault")>] AppIconDefault
    | [<CompiledName("Archive")>] Archive
    | [<CompiledName("AreaChart")>] AreaChart
    | [<CompiledName("Arrivals")>] Arrivals
    | [<CompiledName("ArrowDownRight8")>] ArrowDownRight8
    | [<CompiledName("ArrowDownRightMirrored8")>] ArrowDownRightMirrored8
    | [<CompiledName("ArrowUpRight8")>] ArrowUpRight8
    | [<CompiledName("ArrowUpRightMirrored8")>] ArrowUpRightMirrored8
    | [<CompiledName("Articles")>] Articles
    | [<CompiledName("Ascending")>] Ascending
    | [<CompiledName("AssessmentGroup")>] AssessmentGroup
    | [<CompiledName("AssetLibrary")>] AssetLibrary
    | [<CompiledName("Assign")>] Assign
    | [<CompiledName("Asterisk")>] Asterisk
    | [<CompiledName("ATPLogo")>] ATPLogo
    | [<CompiledName("Attach")>] Attach
    | [<CompiledName("AustralianRules")>] AustralianRules
    | [<CompiledName("AutoEnhanceOff")>] AutoEnhanceOff
    | [<CompiledName("AutoEnhanceOn")>] AutoEnhanceOn
    | [<CompiledName("AutoFillTemplate")>] AutoFillTemplate
    | [<CompiledName("AutoRacing")>] AutoRacing
    | [<CompiledName("AwayStatus")>] AwayStatus
    | [<CompiledName("AzureLogo")>] AzureLogo
    | [<CompiledName("Back")>] Back
    | [<CompiledName("BackToWindow")>] BackToWindow
    | [<CompiledName("Badge")>] Badge
    | [<CompiledName("Balloons")>] Balloons
    | [<CompiledName("BarChart4")>] BarChart4
    | [<CompiledName("BarChartHorizontal")>] BarChartHorizontal
    | [<CompiledName("BarChartVertical")>] BarChartVertical
    | [<CompiledName("Baseball")>] Baseball
    | [<CompiledName("BidiLtr")>] BidiLtr
    | [<CompiledName("BidiRtl")>] BidiRtl
    | [<CompiledName("BingLogo")>] BingLogo
    | [<CompiledName("BlockContact")>] BlockContact
    | [<CompiledName("Blocked")>] Blocked
    | [<CompiledName("Blocked2")>] Blocked2
    | [<CompiledName("BlowingSnow")>] BlowingSnow
    | [<CompiledName("Blur")>] Blur
    | [<CompiledName("Boards")>] Boards
    | [<CompiledName("Bold")>] Bold
    | [<CompiledName("BookingsLogo")>] BookingsLogo
    | [<CompiledName("Bookmarks")>] Bookmarks
    | [<CompiledName("BookmarksMirrored")>] BookmarksMirrored
    | [<CompiledName("BoxLogo")>] BoxLogo
    | [<CompiledName("BranchCommit")>] BranchCommit
    | [<CompiledName("BranchCompare")>] BranchCompare
    | [<CompiledName("BranchFork")>] BranchFork
    | [<CompiledName("BranchFork2")>] BranchFork2
    | [<CompiledName("BranchLocked")>] BranchLocked
    | [<CompiledName("BranchMerge")>] BranchMerge
    | [<CompiledName("BranchPullRequest")>] BranchPullRequest
    | [<CompiledName("BranchSearch")>] BranchSearch
    | [<CompiledName("BranchShelveset")>] BranchShelveset
    | [<CompiledName("Breadcrumb")>] Breadcrumb
    | [<CompiledName("Brightness")>] Brightness
    | [<CompiledName("Broom")>] Broom
    | [<CompiledName("BucketColor")>] BucketColor
    | [<CompiledName("BucketColorFill")>] BucketColorFill
    | [<CompiledName("BufferTimeAfter")>] BufferTimeAfter
    | [<CompiledName("BufferTimeBefore")>] BufferTimeBefore
    | [<CompiledName("BufferTimeBoth")>] BufferTimeBoth
    | [<CompiledName("Build")>] Build
    | [<CompiledName("BuildIssue")>] BuildIssue
    | [<CompiledName("BuildQueue")>] BuildQueue
    | [<CompiledName("BuildQueueNew")>] BuildQueueNew
    | [<CompiledName("BulletedList")>] BulletedList
    | [<CompiledName("BulletedListMirrored")>] BulletedListMirrored
    | [<CompiledName("BusinessHoursSign")>] BusinessHoursSign
    | [<CompiledName("BusSolid")>] BusSolid
    | [<CompiledName("Cafe")>] Cafe
    | [<CompiledName("Cake")>] Cake
    | [<CompiledName("CalculatorAddition")>] CalculatorAddition
    | [<CompiledName("CalculatorSubtract")>] CalculatorSubtract
    | [<CompiledName("Calendar")>] Calendar
    | [<CompiledName("CalendarAgenda")>] CalendarAgenda
    | [<CompiledName("CalendarDay")>] CalendarDay
    | [<CompiledName("CalendarMirrored")>] CalendarMirrored
    | [<CompiledName("CalendarReply")>] CalendarReply
    | [<CompiledName("CalendarWeek")>] CalendarWeek
    | [<CompiledName("CalendarWorkWeek")>] CalendarWorkWeek
    | [<CompiledName("CaloriesAdd")>] CaloriesAdd
    | [<CompiledName("Camera")>] Camera
    | [<CompiledName("Cancel")>] Cancel
    | [<CompiledName("CannedChat")>] CannedChat
    | [<CompiledName("Car")>] Car
    | [<CompiledName("CaretBottomLeftSolid8")>] CaretBottomLeftSolid8
    | [<CompiledName("CaretBottomRightSolid8")>] CaretBottomRightSolid8
    | [<CompiledName("CaretDown8")>] CaretDown8
    | [<CompiledName("CaretDownSolid8")>] CaretDownSolid8
    | [<CompiledName("CaretHollow")>] CaretHollow
    | [<CompiledName("CaretHollowMirrored")>] CaretHollowMirrored
    | [<CompiledName("CaretLeft8")>] CaretLeft8
    | [<CompiledName("CaretLeftSolid8")>] CaretLeftSolid8
    | [<CompiledName("CaretRight")>] CaretRight
    | [<CompiledName("CaretRight8")>] CaretRight8
    | [<CompiledName("CaretRightSolid8")>] CaretRightSolid8
    | [<CompiledName("CaretSolid")>] CaretSolid
    | [<CompiledName("CaretSolid16")>] CaretSolid16
    | [<CompiledName("CaretSolidDown")>] CaretSolidDown
    | [<CompiledName("CaretSolidLeft")>] CaretSolidLeft
    | [<CompiledName("CaretSolidMirrored")>] CaretSolidMirrored
    | [<CompiledName("CaretSolidRight")>] CaretSolidRight
    | [<CompiledName("CaretSolidUp")>] CaretSolidUp
    | [<CompiledName("CaretTopLeftSolid8")>] CaretTopLeftSolid8
    | [<CompiledName("CaretTopRightSolid8")>] CaretTopRightSolid8
    | [<CompiledName("CaretUp8")>] CaretUp8
    | [<CompiledName("CaretUpSolid8")>] CaretUpSolid8
    | [<CompiledName("Cat")>] Cat
    | [<CompiledName("CellPhone")>] CellPhone
    | [<CompiledName("Certificate")>] Certificate
    | [<CompiledName("Chart")>] Chart
    | [<CompiledName("Chat")>] Chat
    | [<CompiledName("ChatInviteFriend")>] ChatInviteFriend
    | [<CompiledName("Checkbox")>] Checkbox
    | [<CompiledName("CheckboxComposite")>] CheckboxComposite
    | [<CompiledName("CheckboxCompositeReversed")>] CheckboxCompositeReversed
    | [<CompiledName("CheckboxIndeterminate")>] CheckboxIndeterminate
    | [<CompiledName("CheckList")>] CheckList
    | [<CompiledName("CheckMark")>] CheckMark
    | [<CompiledName("ChevronDown")>] ChevronDown
    | [<CompiledName("ChevronDownMed")>] ChevronDownMed
    | [<CompiledName("ChevronDownSmall")>] ChevronDownSmall
    | [<CompiledName("ChevronLeft")>] ChevronLeft
    | [<CompiledName("ChevronLeftMed")>] ChevronLeftMed
    | [<CompiledName("ChevronLeftSmall")>] ChevronLeftSmall
    | [<CompiledName("ChevronRight")>] ChevronRight
    | [<CompiledName("ChevronRightMed")>] ChevronRightMed
    | [<CompiledName("ChevronRightSmall")>] ChevronRightSmall
    | [<CompiledName("ChevronUp")>] ChevronUp
    | [<CompiledName("ChevronUpMed")>] ChevronUpMed
    | [<CompiledName("ChevronUpSmall")>] ChevronUpSmall
    | [<CompiledName("ChromeBack")>] ChromeBack
    | [<CompiledName("ChromeBackMirrored")>] ChromeBackMirrored
    | [<CompiledName("ChromeClose")>] ChromeClose
    | [<CompiledName("ChromeMinimize")>] ChromeMinimize
    | [<CompiledName("CircleFill")>] CircleFill
    | [<CompiledName("CircleHalfFull")>] CircleHalfFull
    | [<CompiledName("CirclePlus")>] CirclePlus
    | [<CompiledName("CircleRing")>] CircleRing
    | [<CompiledName("ClassNotebookLogoInverse")>] ClassNotebookLogoInverse
    | [<CompiledName("ClassroomLogo")>] ClassroomLogo
    | [<CompiledName("Clear")>] Clear
    | [<CompiledName("ClearFilter")>] ClearFilter
    | [<CompiledName("ClearFormatting")>] ClearFormatting
    | [<CompiledName("ClearNight")>] ClearNight
    | [<CompiledName("Clock")>] Clock
    | [<CompiledName("CloneToDesktop")>] CloneToDesktop
    | [<CompiledName("ClosedCaption")>] ClosedCaption
    | [<CompiledName("ClosePane")>] ClosePane
    | [<CompiledName("ClosePaneMirrored")>] ClosePaneMirrored
    | [<CompiledName("Cloud")>] Cloud
    | [<CompiledName("CloudAdd")>] CloudAdd
    | [<CompiledName("CloudDownload")>] CloudDownload
    | [<CompiledName("CloudUpload")>] CloudUpload
    | [<CompiledName("CloudWeather")>] CloudWeather
    | [<CompiledName("Cloudy")>] Cloudy
    | [<CompiledName("Cocktails")>] Cocktails
    | [<CompiledName("Code")>] Code
    | [<CompiledName("Coffee")>] Coffee
    | [<CompiledName("CollapseContent")>] CollapseContent
    | [<CompiledName("CollapseContentSingle")>] CollapseContentSingle
    | [<CompiledName("CollapseMenu")>] CollapseMenu
    | [<CompiledName("CollegeFootball")>] CollegeFootball
    | [<CompiledName("CollegeHoops")>] CollegeHoops
    | [<CompiledName("Color")>] Color
    | [<CompiledName("ColumnLeftTwoThirds")>] ColumnLeftTwoThirds
    | [<CompiledName("ColumnOptions")>] ColumnOptions
    | [<CompiledName("ColumnRightTwoThirds")>] ColumnRightTwoThirds
    | [<CompiledName("Combine")>] Combine
    | [<CompiledName("Comment")>] Comment
    | [<CompiledName("CommentUrgent")>] CommentUrgent
    | [<CompiledName("Communications")>] Communications
    | [<CompiledName("CompassNW")>] CompassNW
    | [<CompiledName("Completed")>] Completed
    | [<CompiledName("CompletedSolid")>] CompletedSolid
    | [<CompiledName("Contact")>] Contact
    | [<CompiledName("ContactCard")>] ContactCard
    | [<CompiledName("ContactInfo")>] ContactInfo
    | [<CompiledName("Contrast")>] Contrast
    | [<CompiledName("Copy")>] Copy
    | [<CompiledName("Cotton")>] Cotton
    | [<CompiledName("Cricket")>] Cricket
    | [<CompiledName("CRMReport")>] CRMReport
    | [<CompiledName("CSS")>] CSS
    | [<CompiledName("CustomList")>] CustomList
    | [<CompiledName("CustomListMirrored")>] CustomListMirrored
    | [<CompiledName("Cut")>] Cut
    | [<CompiledName("Cycling")>] Cycling
    | [<CompiledName("DataBarsFill")>] DataBarsFill
    | [<CompiledName("Database")>] Database
    | [<CompiledName("DataConnectionLibrary")>] DataConnectionLibrary
    | [<CompiledName("DateTime")>] DateTime
    | [<CompiledName("DateTime2")>] DateTime2
    | [<CompiledName("DateTimeMirrored")>] DateTimeMirrored
    | [<CompiledName("DecreaseIndentLegacy")>] DecreaseIndentLegacy
    | [<CompiledName("Delete")>] Delete
    | [<CompiledName("DelveAnalytics")>] DelveAnalytics
    | [<CompiledName("DelveAnalyticsLogo")>] DelveAnalyticsLogo
    | [<CompiledName("DelveLogo")>] DelveLogo
    | [<CompiledName("DelveLogoFill")>] DelveLogoFill
    | [<CompiledName("DelveLogoInverse")>] DelveLogoInverse
    | [<CompiledName("Deploy")>] Deploy
    | [<CompiledName("Descending")>] Descending
    | [<CompiledName("Design")>] Design
    | [<CompiledName("DeveloperTools")>] DeveloperTools
    | [<CompiledName("Devices3")>] Devices3
    | [<CompiledName("Devices4")>] Devices4
    | [<CompiledName("Dialpad")>] Dialpad
    | [<CompiledName("Dictionary")>] Dictionary
    | [<CompiledName("DietPlanNotebook")>] DietPlanNotebook
    | [<CompiledName("DiffInline")>] DiffInline
    | [<CompiledName("DiffSideBySide")>] DiffSideBySide
    | [<CompiledName("DisableUpdates")>] DisableUpdates
    | [<CompiledName("Dislike")>] Dislike
    | [<CompiledName("Divider")>] Divider
    | [<CompiledName("DockLeft")>] DockLeft
    | [<CompiledName("DockLeftMirrored")>] DockLeftMirrored
    | [<CompiledName("DockRight")>] DockRight
    | [<CompiledName("DocLibrary")>] DocLibrary
    | [<CompiledName("DocsLogoInverse")>] DocsLogoInverse
    | [<CompiledName("Document")>] Document
    | [<CompiledName("Documentation")>] Documentation
    | [<CompiledName("DocumentReply")>] DocumentReply
    | [<CompiledName("DocumentSearch")>] DocumentSearch
    | [<CompiledName("DocumentSet")>] DocumentSet
    | [<CompiledName("Door")>] Door
    | [<CompiledName("DoubleBookmark")>] DoubleBookmark
    | [<CompiledName("DoubleChevronDown")>] DoubleChevronDown
    | [<CompiledName("DoubleChevronDown12")>] DoubleChevronDown12
    | [<CompiledName("DoubleChevronLeft")>] DoubleChevronLeft
    | [<CompiledName("DoubleChevronLeft12")>] DoubleChevronLeft12
    | [<CompiledName("DoubleChevronLeftMed")>] DoubleChevronLeftMed
    | [<CompiledName("DoubleChevronLeftMedMirrored")>] DoubleChevronLeftMedMirrored
    | [<CompiledName("DoubleChevronRight")>] DoubleChevronRight
    | [<CompiledName("DoubleChevronRight12")>] DoubleChevronRight12
    | [<CompiledName("DoubleChevronUp")>] DoubleChevronUp
    | [<CompiledName("DoubleChevronUp12")>] DoubleChevronUp12
    | [<CompiledName("DoubleColumn")>] DoubleColumn
    | [<CompiledName("Down")>] Down
    | [<CompiledName("Download")>] Download
    | [<CompiledName("DRM")>] DRM
    | [<CompiledName("Drop")>] Drop
    | [<CompiledName("DropboxLogo")>] DropboxLogo
    | [<CompiledName("Dropdown")>] Dropdown
    | [<CompiledName("Duststorm")>] Duststorm
    | [<CompiledName("Dynamics365Logo")>] Dynamics365Logo
    | [<CompiledName("DynamicSMBLogo")>] DynamicSMBLogo
    | [<CompiledName("EatDrink")>] EatDrink
    | [<CompiledName("EdgeLogo")>] EdgeLogo
    | [<CompiledName("Edit")>] Edit
    | [<CompiledName("EditMail")>] EditMail
    | [<CompiledName("EditMirrored")>] EditMirrored
    | [<CompiledName("EditNote")>] EditNote
    | [<CompiledName("EditPhoto")>] EditPhoto
    | [<CompiledName("EditStyle")>] EditStyle
    | [<CompiledName("Embed")>] Embed
    | [<CompiledName("EMI")>] EMI
    | [<CompiledName("Emoji")>] Emoji
    | [<CompiledName("Emoji2")>] Emoji2
    | [<CompiledName("EmojiDisappointed")>] EmojiDisappointed
    | [<CompiledName("EmojiNeutral")>] EmojiNeutral
    | [<CompiledName("EmptyRecycleBin")>] EmptyRecycleBin
    | [<CompiledName("Equalizer")>] Equalizer
    | [<CompiledName("EraseTool")>] EraseTool
    | [<CompiledName("Error")>] Error
    | [<CompiledName("ErrorBadge")>] ErrorBadge
    | [<CompiledName("Event")>] Event
    | [<CompiledName("EventInfo")>] EventInfo
    | [<CompiledName("ExcelDocument")>] ExcelDocument
    | [<CompiledName("ExcelLogo")>] ExcelLogo
    | [<CompiledName("ExcelLogoFill")>] ExcelLogoFill
    | [<CompiledName("ExcelLogoInverse")>] ExcelLogoInverse
    | [<CompiledName("ExchangeLogo")>] ExchangeLogo
    | [<CompiledName("ExchangeLogoFill")>] ExchangeLogoFill
    | [<CompiledName("ExchangeLogoInverse")>] ExchangeLogoInverse
    | [<CompiledName("ExpandMenu")>] ExpandMenu
    | [<CompiledName("ExploreContent")>] ExploreContent
    | [<CompiledName("ExploreContentSingle")>] ExploreContentSingle
    | [<CompiledName("Export")>] Export
    | [<CompiledName("ExportMirrored")>] ExportMirrored
    | [<CompiledName("FabricAssetLibrary")>] FabricAssetLibrary
    | [<CompiledName("FabricDataConnectionLibrary")>] FabricDataConnectionLibrary
    | [<CompiledName("FabricDocLibrary")>] FabricDocLibrary
    | [<CompiledName("FabricFolder")>] FabricFolder
    | [<CompiledName("FabricFolderFill")>] FabricFolderFill
    | [<CompiledName("FabricFolderSearch")>] FabricFolderSearch
    | [<CompiledName("FabricFormLibrary")>] FabricFormLibrary
    | [<CompiledName("FabricFormLibraryMirrored")>] FabricFormLibraryMirrored
    | [<CompiledName("FabricMovetoFolder")>] FabricMovetoFolder
    | [<CompiledName("FabricNewFolder")>] FabricNewFolder
    | [<CompiledName("FabricOpenFolderHorizontal")>] FabricOpenFolderHorizontal
    | [<CompiledName("FabricPictureLibrary")>] FabricPictureLibrary
    | [<CompiledName("FabricPublicFolder")>] FabricPublicFolder
    | [<CompiledName("FabricReportLibrary")>] FabricReportLibrary
    | [<CompiledName("FabricReportLibraryMirrored")>] FabricReportLibraryMirrored
    | [<CompiledName("FabricSyncFolder")>] FabricSyncFolder
    | [<CompiledName("FabricUnsyncFolder")>] FabricUnsyncFolder
    | [<CompiledName("FacebookLogo")>] FacebookLogo
    | [<CompiledName("Family")>] Family
    | [<CompiledName("FangBody")>] FangBody
    | [<CompiledName("FastForward")>] FastForward
    | [<CompiledName("Favicon")>] Favicon
    | [<CompiledName("FavoriteList")>] FavoriteList
    | [<CompiledName("FavoriteStar")>] FavoriteStar
    | [<CompiledName("FavoriteStarFill")>] FavoriteStarFill
    | [<CompiledName("Fax")>] Fax
    | [<CompiledName("Ferry")>] Ferry
    | [<CompiledName("FerrySolid")>] FerrySolid
    | [<CompiledName("FileBug")>] FileBug
    | [<CompiledName("FileCode")>] FileCode
    | [<CompiledName("FileComment")>] FileComment
    | [<CompiledName("FileImage")>] FileImage
    | [<CompiledName("FileSymlink")>] FileSymlink
    | [<CompiledName("Filter")>] Filter
    | [<CompiledName("Filters")>] Filters
    | [<CompiledName("Financial")>] Financial
    | [<CompiledName("Fingerprint")>] Fingerprint
    | [<CompiledName("FiveTileGrid")>] FiveTileGrid
    | [<CompiledName("Flag")>] Flag
    | [<CompiledName("FlameSolid")>] FlameSolid
    | [<CompiledName("FlickDown")>] FlickDown
    | [<CompiledName("FlickLeft")>] FlickLeft
    | [<CompiledName("FlickRight")>] FlickRight
    | [<CompiledName("FlickUp")>] FlickUp
    | [<CompiledName("Flow")>] Flow
    | [<CompiledName("FocalPoint")>] FocalPoint
    | [<CompiledName("Fog")>] Fog
    | [<CompiledName("Folder")>] Folder
    | [<CompiledName("FolderFill")>] FolderFill
    | [<CompiledName("FolderHorizontal")>] FolderHorizontal
    | [<CompiledName("FolderOpen")>] FolderOpen
    | [<CompiledName("FolderSearch")>] FolderSearch
    | [<CompiledName("Font")>] Font
    | [<CompiledName("FontColor")>] FontColor
    | [<CompiledName("FontDecrease")>] FontDecrease
    | [<CompiledName("FontIncrease")>] FontIncrease
    | [<CompiledName("FontSize")>] FontSize
    | [<CompiledName("FormLibrary")>] FormLibrary
    | [<CompiledName("FormLibraryMirrored")>] FormLibraryMirrored
    | [<CompiledName("Forward")>] Forward
    | [<CompiledName("ForwardEvent")>] ForwardEvent
    | [<CompiledName("Freezing")>] Freezing
    | [<CompiledName("Frigid")>] Frigid
    | [<CompiledName("FullCircleMask")>] FullCircleMask
    | [<CompiledName("FullHistory")>] FullHistory
    | [<CompiledName("FullScreen")>] FullScreen
    | [<CompiledName("FullWidth")>] FullWidth
    | [<CompiledName("Generate")>] Generate
    | [<CompiledName("Giftbox")>] Giftbox
    | [<CompiledName("GiftboxOpen")>] GiftboxOpen
    | [<CompiledName("GiftCard")>] GiftCard
    | [<CompiledName("Glasses")>] Glasses
    | [<CompiledName("Glimmer")>] Glimmer
    | [<CompiledName("GlobalNavButton")>] GlobalNavButton
    | [<CompiledName("Globe")>] Globe
    | [<CompiledName("GlobeFavorite")>] GlobeFavorite
    | [<CompiledName("Golf")>] Golf
    | [<CompiledName("GoogleDriveLogo")>] GoogleDriveLogo
    | [<CompiledName("GotoToday")>] GotoToday
    | [<CompiledName("GripperBarVertical")>] GripperBarVertical
    | [<CompiledName("GripperTool")>] GripperTool
    | [<CompiledName("Group")>] Group
    | [<CompiledName("GroupedAscending")>] GroupedAscending
    | [<CompiledName("GroupedDescending")>] GroupedDescending
    | [<CompiledName("GroupedList")>] GroupedList
    | [<CompiledName("HailDay")>] HailDay
    | [<CompiledName("HailNight")>] HailNight
    | [<CompiledName("Handwriting")>] Handwriting
    | [<CompiledName("HardDriveGroup")>] HardDriveGroup
    | [<CompiledName("Header1")>] Header1
    | [<CompiledName("Header2")>] Header2
    | [<CompiledName("Header3")>] Header3
    | [<CompiledName("Header4")>] Header4
    | [<CompiledName("Headset")>] Headset
    | [<CompiledName("Health")>] Health
    | [<CompiledName("Heart")>] Heart
    | [<CompiledName("HeartFill")>] HeartFill
    | [<CompiledName("Help")>] Help
    | [<CompiledName("HelpMirrored")>] HelpMirrored
    | [<CompiledName("Hide")>] Hide
    | [<CompiledName("Hide2")>] Hide2
    | [<CompiledName("Highlight")>] Highlight
    | [<CompiledName("HighlightMappedShapes")>] HighlightMappedShapes
    | [<CompiledName("History")>] History
    | [<CompiledName("Home")>] Home
    | [<CompiledName("HomeSolid")>] HomeSolid
    | [<CompiledName("Hospital")>] Hospital
    | [<CompiledName("Hotel")>] Hotel
    | [<CompiledName("IconSetsFlag")>] IconSetsFlag
    | [<CompiledName("IconSetsFlagFill")>] IconSetsFlagFill
    | [<CompiledName("ImageDiff")>] ImageDiff
    | [<CompiledName("ImagePixel")>] ImagePixel
    | [<CompiledName("Important")>] Important
    | [<CompiledName("InboxCheck")>] InboxCheck
    | [<CompiledName("IncidentTriangle")>] IncidentTriangle
    | [<CompiledName("IncreaseIndentLegacy")>] IncreaseIndentLegacy
    | [<CompiledName("Info")>] Info
    | [<CompiledName("Info2")>] Info2
    | [<CompiledName("InfoSolid")>] InfoSolid
    | [<CompiledName("InsertTextBox")>] InsertTextBox
    | [<CompiledName("InstallToDrive")>] InstallToDrive
    | [<CompiledName("InternetSharing")>] InternetSharing
    | [<CompiledName("iOSAppStoreLogo")>] IOSAppStoreLogo
    | [<CompiledName("IssueTracking")>] IssueTracking
    | [<CompiledName("IssueTrackingMirrored")>] IssueTrackingMirrored
    | [<CompiledName("Italic")>] Italic
    | [<CompiledName("JoinOnlineMeeting")>] JoinOnlineMeeting
    | [<CompiledName("JS")>] JS
    | [<CompiledName("Label")>] Label
    | [<CompiledName("LandscapeOrientation")>] LandscapeOrientation
    | [<CompiledName("LaptopSelected")>] LaptopSelected
    | [<CompiledName("LargeGrid")>] LargeGrid
    | [<CompiledName("Library")>] Library
    | [<CompiledName("Lifesaver")>] Lifesaver
    | [<CompiledName("LifesaverLock")>] LifesaverLock
    | [<CompiledName("Light")>] Light
    | [<CompiledName("Lightbulb")>] Lightbulb
    | [<CompiledName("LightningBolt")>] LightningBolt
    | [<CompiledName("Like")>] Like
    | [<CompiledName("LikeSolid")>] LikeSolid
    | [<CompiledName("LineChart")>] LineChart
    | [<CompiledName("Link")>] Link
    | [<CompiledName("List")>] List
    | [<CompiledName("ListMirrored")>] ListMirrored
    | [<CompiledName("Location")>] Location
    | [<CompiledName("LocationCircle")>] LocationCircle
    | [<CompiledName("LocationDot")>] LocationDot
    | [<CompiledName("LocationFill")>] LocationFill
    | [<CompiledName("Lock")>] Lock
    | [<CompiledName("LockSolid")>] LockSolid
    | [<CompiledName("LogRemove")>] LogRemove
    | [<CompiledName("LowerBrightness")>] LowerBrightness
    | [<CompiledName("LyncLogo")>] LyncLogo
    | [<CompiledName("Mail")>] Mail
    | [<CompiledName("MailAlert")>] MailAlert
    | [<CompiledName("MailCheck")>] MailCheck
    | [<CompiledName("MailFill")>] MailFill
    | [<CompiledName("MailForward")>] MailForward
    | [<CompiledName("MailForwardMirrored")>] MailForwardMirrored
    | [<CompiledName("MailLowImportance")>] MailLowImportance
    | [<CompiledName("MailPause")>] MailPause
    | [<CompiledName("MailRepeat")>] MailRepeat
    | [<CompiledName("MailReply")>] MailReply
    | [<CompiledName("MailReplyAll")>] MailReplyAll
    | [<CompiledName("MailReplyAllMirrored")>] MailReplyAllMirrored
    | [<CompiledName("MailReplyMirrored")>] MailReplyMirrored
    | [<CompiledName("MapDirections")>] MapDirections
    | [<CompiledName("MapPin")>] MapPin
    | [<CompiledName("Market")>] Market
    | [<CompiledName("MarketDown")>] MarketDown
    | [<CompiledName("Megaphone")>] Megaphone
    | [<CompiledName("Memo")>] Memo
    | [<CompiledName("Merge")>] Merge
    | [<CompiledName("MergeDuplicate")>] MergeDuplicate
    | [<CompiledName("Message")>] Message
    | [<CompiledName("MessageFill")>] MessageFill
    | [<CompiledName("Microphone")>] Microphone
    | [<CompiledName("MicrosoftStaffhubLogo")>] MicrosoftStaffhubLogo
    | [<CompiledName("MiniLink")>] MiniLink
    | [<CompiledName("MobileSelected")>] MobileSelected
    | [<CompiledName("Money")>] Money
    | [<CompiledName("More")>] More
    | [<CompiledName("MoreSports")>] MoreSports
    | [<CompiledName("MoreVertical")>] MoreVertical
    | [<CompiledName("Move")>] Move
    | [<CompiledName("MoveToFolder")>] MoveToFolder
    | [<CompiledName("MSNLogo")>] MSNLogo
    | [<CompiledName("MSNVideos")>] MSNVideos
    | [<CompiledName("MultiSelect")>] MultiSelect
    | [<CompiledName("MultiSelectMirrored")>] MultiSelectMirrored
    | [<CompiledName("MusicInCollection")>] MusicInCollection
    | [<CompiledName("MusicInCollectionFill")>] MusicInCollectionFill
    | [<CompiledName("MusicNote")>] MusicNote
    | [<CompiledName("Nav2DMapView")>] Nav2DMapView
    | [<CompiledName("NetworkTower")>] NetworkTower
    | [<CompiledName("NewAnalyticsQuery")>] NewAnalyticsQuery
    | [<CompiledName("NewFolder")>] NewFolder
    | [<CompiledName("News")>] News
    | [<CompiledName("Next")>] Next
    | [<CompiledName("NoteForward")>] NoteForward
    | [<CompiledName("NotePinned")>] NotePinned
    | [<CompiledName("NoteReply")>] NoteReply
    | [<CompiledName("NumberedList")>] NumberedList
    | [<CompiledName("NumberField")>] NumberField
    | [<CompiledName("OfficeAddinsLogo")>] OfficeAddinsLogo
    | [<CompiledName("OfficeAssistantLogo")>] OfficeAssistantLogo
    | [<CompiledName("OfficeFormLogo")>] OfficeFormLogo
    | [<CompiledName("OfficeLogo")>] OfficeLogo
    | [<CompiledName("OfficeStoreLogo")>] OfficeStoreLogo
    | [<CompiledName("OfficeVideoLogo")>] OfficeVideoLogo
    | [<CompiledName("OfficeVideoLogoFill")>] OfficeVideoLogoFill
    | [<CompiledName("OfficeVideoLogoInverse")>] OfficeVideoLogoInverse
    | [<CompiledName("OfflineOneDriveParachute")>] OfflineOneDriveParachute
    | [<CompiledName("OfflineOneDriveParachuteDisabled")>] OfflineOneDriveParachuteDisabled
    | [<CompiledName("OneDrive")>] OneDrive
    | [<CompiledName("OneDriveAdd")>] OneDriveAdd
    | [<CompiledName("OneNoteEduLogoInverse")>] OneNoteEduLogoInverse
    | [<CompiledName("OneNoteLogo")>] OneNoteLogo
    | [<CompiledName("OneNoteLogoFill")>] OneNoteLogoFill
    | [<CompiledName("OneNoteLogoInverse")>] OneNoteLogoInverse
    | [<CompiledName("OpenFile")>] OpenFile
    | [<CompiledName("OpenFolderHorizontal")>] OpenFolderHorizontal
    | [<CompiledName("OpenInNewWindow")>] OpenInNewWindow
    | [<CompiledName("OpenPane")>] OpenPane
    | [<CompiledName("OpenPaneMirrored")>] OpenPaneMirrored
    | [<CompiledName("OpenSource")>] OpenSource
    | [<CompiledName("Org")>] Org
    | [<CompiledName("OutlookLogo")>] OutlookLogo
    | [<CompiledName("OutlookLogoFill")>] OutlookLogoFill
    | [<CompiledName("OutlookLogoInverse")>] OutlookLogoInverse
    | [<CompiledName("OutOfOffice")>] OutOfOffice
    | [<CompiledName("Package")>] Package
    | [<CompiledName("Packages")>] Packages
    | [<CompiledName("Page")>] Page
    | [<CompiledName("PageAdd")>] PageAdd
    | [<CompiledName("PageCheckedin")>] PageCheckedin
    | [<CompiledName("PageCheckedOut")>] PageCheckedOut
    | [<CompiledName("PageLeft")>] PageLeft
    | [<CompiledName("PageRight")>] PageRight
    | [<CompiledName("PageSolid")>] PageSolid
    | [<CompiledName("PanoIndicator")>] PanoIndicator
    | [<CompiledName("Parameter")>] Parameter
    | [<CompiledName("ParatureLogo")>] ParatureLogo
    | [<CompiledName("PartlyCloudyDay")>] PartlyCloudyDay
    | [<CompiledName("PartlyCloudyNight")>] PartlyCloudyNight
    | [<CompiledName("PartyLeader")>] PartyLeader
    | [<CompiledName("Paste")>] Paste
    | [<CompiledName("Pause")>] Pause
    | [<CompiledName("PaymentCard")>] PaymentCard
    | [<CompiledName("PC1")>] PC1
    | [<CompiledName("PDF")>] PDF
    | [<CompiledName("PencilReply")>] PencilReply
    | [<CompiledName("People")>] People
    | [<CompiledName("PeopleAdd")>] PeopleAdd
    | [<CompiledName("PeopleAlert")>] PeopleAlert
    | [<CompiledName("PeopleBlock")>] PeopleBlock
    | [<CompiledName("PeoplePause")>] PeoplePause
    | [<CompiledName("PeopleRepeat")>] PeopleRepeat
    | [<CompiledName("Permissions")>] Permissions
    | [<CompiledName("Personalize")>] Personalize
    | [<CompiledName("Phone")>] Phone
    | [<CompiledName("Photo2")>] Photo2
    | [<CompiledName("Photo2Add")>] Photo2Add
    | [<CompiledName("Photo2Remove")>] Photo2Remove
    | [<CompiledName("PhotoCollection")>] PhotoCollection
    | [<CompiledName("Picture")>] Picture
    | [<CompiledName("PictureLibrary")>] PictureLibrary
    | [<CompiledName("PieDouble")>] PieDouble
    | [<CompiledName("PieSingle")>] PieSingle
    | [<CompiledName("Pill")>] Pill
    | [<CompiledName("Pin")>] Pin
    | [<CompiledName("Pinned")>] Pinned
    | [<CompiledName("PinnedFill")>] PinnedFill
    | [<CompiledName("PivotChart")>] PivotChart
    | [<CompiledName("PlannerLogo")>] PlannerLogo
    | [<CompiledName("Play")>] Play
    | [<CompiledName("PlayerSettings")>] PlayerSettings
    | [<CompiledName("Plug")>] Plug
    | [<CompiledName("PlugConnected")>] PlugConnected
    | [<CompiledName("PlugDisconnected")>] PlugDisconnected
    | [<CompiledName("PlugSolid")>] PlugSolid
    | [<CompiledName("POI")>] POI
    | [<CompiledName("PostUpdate")>] PostUpdate
    | [<CompiledName("PowerApps")>] PowerApps
    | [<CompiledName("PowerApps2Logo")>] PowerApps2Logo
    | [<CompiledName("PowerAppsLogo")>] PowerAppsLogo
    | [<CompiledName("PowerBILogo")>] PowerBILogo
    | [<CompiledName("PowerPointDocument")>] PowerPointDocument
    | [<CompiledName("PowerPointLogo")>] PowerPointLogo
    | [<CompiledName("PowerPointLogoFill")>] PowerPointLogoFill
    | [<CompiledName("PowerPointLogoInverse")>] PowerPointLogoInverse
    | [<CompiledName("Precipitation")>] Precipitation
    | [<CompiledName("PresenceChickletVideo")>] PresenceChickletVideo
    | [<CompiledName("Preview")>] Preview
    | [<CompiledName("PreviewLink")>] PreviewLink
    | [<CompiledName("Previous")>] Previous
    | [<CompiledName("Print")>] Print
    | [<CompiledName("PrintfaxPrinterFile")>] PrintfaxPrinterFile
    | [<CompiledName("Processing")>] Processing
    | [<CompiledName("ProcessMetaTask")>] ProcessMetaTask
    | [<CompiledName("Product")>] Product
    | [<CompiledName("ProFootball")>] ProFootball
    | [<CompiledName("ProgressRingDots")>] ProgressRingDots
    | [<CompiledName("ProHockey")>] ProHockey
    | [<CompiledName("ProjectLogoInverse")>] ProjectLogoInverse
    | [<CompiledName("ProtectedDocument")>] ProtectedDocument
    | [<CompiledName("ProtectRestrict")>] ProtectRestrict
    | [<CompiledName("PublicCalendar")>] PublicCalendar
    | [<CompiledName("PublicContactCard")>] PublicContactCard
    | [<CompiledName("PublicEmail")>] PublicEmail
    | [<CompiledName("PublicFolder")>] PublicFolder
    | [<CompiledName("PublisherLogo")>] PublisherLogo
    | [<CompiledName("PublisherLogoFill")>] PublisherLogoFill
    | [<CompiledName("Puzzle")>] Puzzle
    | [<CompiledName("Questionnaire")>] Questionnaire
    | [<CompiledName("QuestionnaireMirrored")>] QuestionnaireMirrored
    | [<CompiledName("QuickNote")>] QuickNote
    | [<CompiledName("RadioBtnOff")>] RadioBtnOff
    | [<CompiledName("RadioBtnOn")>] RadioBtnOn
    | [<CompiledName("RadioBullet")>] RadioBullet
    | [<CompiledName("Rain")>] Rain
    | [<CompiledName("RainShowersDay")>] RainShowersDay
    | [<CompiledName("RainShowersNight")>] RainShowersNight
    | [<CompiledName("RainSnow")>] RainSnow
    | [<CompiledName("RawSource")>] RawSource
    | [<CompiledName("Read")>] Read
    | [<CompiledName("ReadingMode")>] ReadingMode
    | [<CompiledName("ReceiptCheck")>] ReceiptCheck
    | [<CompiledName("ReceiptForward")>] ReceiptForward
    | [<CompiledName("ReceiptReply")>] ReceiptReply
    | [<CompiledName("Recent")>] Recent
    | [<CompiledName("Record2")>] Record2
    | [<CompiledName("RecurringEvent")>] RecurringEvent
    | [<CompiledName("RecurringTask")>] RecurringTask
    | [<CompiledName("RecycleBin")>] RecycleBin
    | [<CompiledName("Redeploy")>] Redeploy
    | [<CompiledName("RedEye")>] RedEye
    | [<CompiledName("Redo")>] Redo
    | [<CompiledName("Refresh")>] Refresh
    | [<CompiledName("ReminderGroup")>] ReminderGroup
    | [<CompiledName("Remove")>] Remove
    | [<CompiledName("RemoveEvent")>] RemoveEvent
    | [<CompiledName("RemoveFilter")>] RemoveFilter
    | [<CompiledName("RemoveLink")>] RemoveLink
    | [<CompiledName("RemoveOccurrence")>] RemoveOccurrence
    | [<CompiledName("Rename")>] Rename
    | [<CompiledName("ReopenPages")>] ReopenPages
    | [<CompiledName("Repair")>] Repair
    | [<CompiledName("Reply")>] Reply
    | [<CompiledName("ReplyAll")>] ReplyAll
    | [<CompiledName("ReplyAllAlt")>] ReplyAllAlt
    | [<CompiledName("ReplyAllMirrored")>] ReplyAllMirrored
    | [<CompiledName("ReplyAlt")>] ReplyAlt
    | [<CompiledName("ReplyMirrored")>] ReplyMirrored
    | [<CompiledName("ReportLibrary")>] ReportLibrary
    | [<CompiledName("ReportLibraryMirrored")>] ReportLibraryMirrored
    | [<CompiledName("ReturnToSession")>] ReturnToSession
    | [<CompiledName("RevToggleKey")>] RevToggleKey
    | [<CompiledName("Rewind")>] Rewind
    | [<CompiledName("Ribbon")>] Ribbon
    | [<CompiledName("RightDoubleQuote")>] RightDoubleQuote
    | [<CompiledName("Ringer")>] Ringer
    | [<CompiledName("Robot")>] Robot
    | [<CompiledName("Room")>] Room
    | [<CompiledName("Rotate")>] Rotate
    | [<CompiledName("RowsChild")>] RowsChild
    | [<CompiledName("RowsGroup")>] RowsGroup
    | [<CompiledName("Rugby")>] Rugby
    | [<CompiledName("Running")>] Running
    | [<CompiledName("Sad")>] Sad
    | [<CompiledName("Save")>] Save
    | [<CompiledName("SaveAll")>] SaveAll
    | [<CompiledName("SaveAs")>] SaveAs
    | [<CompiledName("ScheduleEventAction")>] ScheduleEventAction
    | [<CompiledName("Script")>] Script
    | [<CompiledName("ScrollUpDown")>] ScrollUpDown
    | [<CompiledName("Search")>] Search
    | [<CompiledName("Section")>] Section
    | [<CompiledName("Sections")>] Sections
    | [<CompiledName("SecurityGroup")>] SecurityGroup
    | [<CompiledName("Send")>] Send
    | [<CompiledName("SendMirrored")>] SendMirrored
    | [<CompiledName("Server")>] Server
    | [<CompiledName("ServerEnviroment")>] ServerEnviroment
    | [<CompiledName("ServerProcesses")>] ServerProcesses
    | [<CompiledName("SetAction")>] SetAction
    | [<CompiledName("Settings")>] Settings
    | [<CompiledName("Share")>] Share
    | [<CompiledName("ShareiOS")>] ShareiOS
    | [<CompiledName("SharepointLogo")>] SharepointLogo
    | [<CompiledName("SharepointLogoFill")>] SharepointLogoFill
    | [<CompiledName("SharepointLogoInverse")>] SharepointLogoInverse
    | [<CompiledName("Shield")>] Shield
    | [<CompiledName("Shop")>] Shop
    | [<CompiledName("ShoppingCart")>] ShoppingCart
    | [<CompiledName("ShowResults")>] ShowResults
    | [<CompiledName("ShowResultsMirrored")>] ShowResultsMirrored
    | [<CompiledName("SidePanel")>] SidePanel
    | [<CompiledName("SingleBookmark")>] SingleBookmark
    | [<CompiledName("SingleColumn")>] SingleColumn
    | [<CompiledName("SIPMove")>] SIPMove
    | [<CompiledName("SkypeCheck")>] SkypeCheck
    | [<CompiledName("SkypeCircleCheck")>] SkypeCircleCheck
    | [<CompiledName("SkypeCircleClock")>] SkypeCircleClock
    | [<CompiledName("SkypeCircleMinus")>] SkypeCircleMinus
    | [<CompiledName("SkypeClock")>] SkypeClock
    | [<CompiledName("SkypeForBusinessLogoFill")>] SkypeForBusinessLogoFill
    | [<CompiledName("SkypeLogo")>] SkypeLogo
    | [<CompiledName("SkypeMessage")>] SkypeMessage
    | [<CompiledName("SkypeMinus")>] SkypeMinus
    | [<CompiledName("SliderThumb")>] SliderThumb
    | [<CompiledName("Snow")>] Snow
    | [<CompiledName("Snowflake")>] Snowflake
    | [<CompiledName("SnowShowerDay")>] SnowShowerDay
    | [<CompiledName("SnowShowerNight")>] SnowShowerNight
    | [<CompiledName("Soccer")>] Soccer
    | [<CompiledName("SocialListeningLogo")>] SocialListeningLogo
    | [<CompiledName("Sort")>] Sort
    | [<CompiledName("SortDown")>] SortDown
    | [<CompiledName("SortLines")>] SortLines
    | [<CompiledName("SortUp")>] SortUp
    | [<CompiledName("Spacer")>] Spacer
    | [<CompiledName("Speakers")>] Speakers
    | [<CompiledName("SpeedHigh")>] SpeedHigh
    | [<CompiledName("Split")>] Split
    | [<CompiledName("Squalls")>] Squalls
    | [<CompiledName("StackedBarChart")>] StackedBarChart
    | [<CompiledName("StackedLineChart")>] StackedLineChart
    | [<CompiledName("StackIndicator")>] StackIndicator
    | [<CompiledName("Starburst")>] Starburst
    | [<CompiledName("StatusErrorFull")>] StatusErrorFull
    | [<CompiledName("StatusTriangle")>] StatusTriangle
    | [<CompiledName("Step")>] Step
    | [<CompiledName("StepInsert")>] StepInsert
    | [<CompiledName("StepShared")>] StepShared
    | [<CompiledName("StepSharedAdd")>] StepSharedAdd
    | [<CompiledName("StepSharedInsert")>] StepSharedInsert
    | [<CompiledName("StockDown")>] StockDown
    | [<CompiledName("StockUp")>] StockUp
    | [<CompiledName("Stop")>] Stop
    | [<CompiledName("StopSolid")>] StopSolid
    | [<CompiledName("Stopwatch")>] Stopwatch
    | [<CompiledName("StoreLogo")>] StoreLogo
    | [<CompiledName("StoreLogoMed")>] StoreLogoMed
    | [<CompiledName("Storyboard")>] Storyboard
    | [<CompiledName("Streaming")>] Streaming
    | [<CompiledName("StreamLogo")>] StreamLogo
    | [<CompiledName("Strikethrough")>] Strikethrough
    | [<CompiledName("Subscribe")>] Subscribe
    | [<CompiledName("Subscript")>] Subscript
    | [<CompiledName("Suitcase")>] Suitcase
    | [<CompiledName("SunAdd")>] SunAdd
    | [<CompiledName("Sunny")>] Sunny
    | [<CompiledName("SunQuestionMark")>] SunQuestionMark
    | [<CompiledName("Superscript")>] Superscript
    | [<CompiledName("SwayLogoInverse")>] SwayLogoInverse
    | [<CompiledName("Switch")>] Switch
    | [<CompiledName("SwitcherStartEnd")>] SwitcherStartEnd
    | [<CompiledName("Sync")>] Sync
    | [<CompiledName("SyncFolder")>] SyncFolder
    | [<CompiledName("SyncToPC")>] SyncToPC
    | [<CompiledName("System")>] System
    | [<CompiledName("Tab")>] Tab
    | [<CompiledName("Table")>] Table
    | [<CompiledName("Tablet")>] Tablet
    | [<CompiledName("TabletSelected")>] TabletSelected
    | [<CompiledName("Tag")>] Tag
    | [<CompiledName("TaskManager")>] TaskManager
    | [<CompiledName("TaskManagerMirrored")>] TaskManagerMirrored
    | [<CompiledName("TeamsLogo")>] TeamsLogo
    | [<CompiledName("TeamsLogoFill")>] TeamsLogoFill
    | [<CompiledName("TeamsLogoInverse")>] TeamsLogoInverse
    | [<CompiledName("Teamwork")>] Teamwork
    | [<CompiledName("TemporaryUser")>] TemporaryUser
    | [<CompiledName("Tennis")>] Tennis
    | [<CompiledName("TextBox")>] TextBox
    | [<CompiledName("TextCallout")>] TextCallout
    | [<CompiledName("TextCalloutFill")>] TextCalloutFill
    | [<CompiledName("TextDocument")>] TextDocument
    | [<CompiledName("TextField")>] TextField
    | [<CompiledName("ThumbnailView")>] ThumbnailView
    | [<CompiledName("ThumbnailViewMirrored")>] ThumbnailViewMirrored
    | [<CompiledName("Thunderstorms")>] Thunderstorms
    | [<CompiledName("Ticket")>] Ticket
    | [<CompiledName("Tiles")>] Tiles
    | [<CompiledName("Tiles2")>] Tiles2
    | [<CompiledName("Timeline")>] Timeline
    | [<CompiledName("Timer")>] Timer
    | [<CompiledName("ToggleBorder")>] ToggleBorder
    | [<CompiledName("ToggleFilled")>] ToggleFilled
    | [<CompiledName("ToggleThumb")>] ToggleThumb
    | [<CompiledName("Touch")>] Touch
    | [<CompiledName("TouchPointer")>] TouchPointer
    | [<CompiledName("Train")>] Train
    | [<CompiledName("TrainSolid")>] TrainSolid
    | [<CompiledName("TransferCall")>] TransferCall
    | [<CompiledName("TriangleDown12")>] TriangleDown12
    | [<CompiledName("TriangleLeft12")>] TriangleLeft12
    | [<CompiledName("TriangleRight12")>] TriangleRight12
    | [<CompiledName("TriangleSolid")>] TriangleSolid
    | [<CompiledName("TriangleSolidDown12")>] TriangleSolidDown12
    | [<CompiledName("TriangleSolidLeft12")>] TriangleSolidLeft12
    | [<CompiledName("TriangleSolidRight12")>] TriangleSolidRight12
    | [<CompiledName("TriangleSolidUp12")>] TriangleSolidUp12
    | [<CompiledName("TriangleUp12")>] TriangleUp12
    | [<CompiledName("TriggerAuto")>] TriggerAuto
    | [<CompiledName("TriggerUser")>] TriggerUser
    | [<CompiledName("TripleColumn")>] TripleColumn
    | [<CompiledName("Trophy")>] Trophy
    | [<CompiledName("TurnRight")>] TurnRight
    | [<CompiledName("TVMonitor")>] TVMonitor
    | [<CompiledName("TVMonitorSelected")>] TVMonitorSelected
    | [<CompiledName("Underline")>] Underline
    | [<CompiledName("Undo")>] Undo
    | [<CompiledName("Unfavorite")>] Unfavorite
    | [<CompiledName("Unknown")>] Unknown
    | [<CompiledName("UnknownCall")>] UnknownCall
    | [<CompiledName("Unlock")>] Unlock
    | [<CompiledName("UnlockSolid")>] UnlockSolid
    | [<CompiledName("Unpin")>] Unpin
    | [<CompiledName("Unsubscribe")>] Unsubscribe
    | [<CompiledName("UnsyncFolder")>] UnsyncFolder
    | [<CompiledName("Up")>] Up
    | [<CompiledName("Upload")>] Upload
    | [<CompiledName("Variable")>] Variable
    | [<CompiledName("VariableGroup")>] VariableGroup
    | [<CompiledName("VennDiagram")>] VennDiagram
    | [<CompiledName("Video")>] Video
    | [<CompiledName("VideoSolid")>] VideoSolid
    | [<CompiledName("View")>] View
    | [<CompiledName("ViewAll")>] ViewAll
    | [<CompiledName("ViewAll2")>] ViewAll2
    | [<CompiledName("ViewDashboard")>] ViewDashboard
    | [<CompiledName("ViewList")>] ViewList
    | [<CompiledName("ViewListGroup")>] ViewListGroup
    | [<CompiledName("ViewListTree")>] ViewListTree
    | [<CompiledName("VisioDiagram")>] VisioDiagram
    | [<CompiledName("VisioDocument")>] VisioDocument
    | [<CompiledName("VisioLogo")>] VisioLogo
    | [<CompiledName("VisioLogoFill")>] VisioLogoFill
    | [<CompiledName("VisioLogoInverse")>] VisioLogoInverse
    | [<CompiledName("VoicemailForward")>] VoicemailForward
    | [<CompiledName("VoicemailReply")>] VoicemailReply
    | [<CompiledName("Volume0")>] Volume0
    | [<CompiledName("Volume1")>] Volume1
    | [<CompiledName("Volume2")>] Volume2
    | [<CompiledName("Volume3")>] Volume3
    | [<CompiledName("VolumeDisabled")>] VolumeDisabled
    | [<CompiledName("Waffle")>] Waffle
    | [<CompiledName("Warning")>] Warning
    | [<CompiledName("Website")>] Website
    | [<CompiledName("Weights")>] Weights
    | [<CompiledName("WifiEthernet")>] WifiEthernet
    | [<CompiledName("WindDirection")>] WindDirection
    | [<CompiledName("WindowsLogo")>] WindowsLogo
    | [<CompiledName("WipePhone")>] WipePhone
    | [<CompiledName("WordDocument")>] WordDocument
    | [<CompiledName("WordLogo")>] WordLogo
    | [<CompiledName("WordLogoFill")>] WordLogoFill
    | [<CompiledName("WordLogoInverse")>] WordLogoInverse
    | [<CompiledName("Work")>] Work
    | [<CompiledName("WorkFlow")>] WorkFlow
    | [<CompiledName("WorkItem")>] WorkItem
    | [<CompiledName("WorkItemBug")>] WorkItemBug
    | [<CompiledName("WorldClock")>] WorldClock
    | [<CompiledName("YammerLogo")>] YammerLogo
    | [<CompiledName("Zoom")>] Zoom
    | [<CompiledName("ZoomIn")>] ZoomIn
    | [<CompiledName("ZoomOut")>] ZoomOut
    | [<CompiledName("FilterSolid")>] FilterSolid
    | [<CompiledName("GridViewSmall")>] GridViewSmall
    | [<CompiledName("GridViewMedium")>] GridViewMedium
    | [<CompiledName("GridViewLarge")>] GridViewLarge
    | [<CompiledName("ThisPc")>] ThisPc
    | [<CompiledName("MailUndelivered")>] MailUndelivered
    | [<CompiledName("MailTentative")>] MailTentative
    | [<CompiledName("MailTentativeMirrored")>] MailTentativeMirrored
    | [<CompiledName("MailReminder")>] MailReminder
    | [<CompiledName("IRMReply")>] IRMReply
    | [<CompiledName("IRMReplyMirrored")>] IRMReplyMirrored
    | [<CompiledName("IRMForward")>] IRMForward
    | [<CompiledName("IRMForwardMirrored")>] IRMForwardMirrored
    | [<CompiledName("ReceiptUndelivered")>] ReceiptUndelivered
    | [<CompiledName("ReceiptTentative")>] ReceiptTentative
    | [<CompiledName("ReceiptTentativeMirrored")>] ReceiptTentativeMirrored
    | [<CompiledName("Inbox")>] Inbox
    | [<CompiledName("VoicemailRM")>] VoicemailRM
    | [<CompiledName("EventAccepted")>] EventAccepted
    | [<CompiledName("EventTentative")>] EventTentative
    | [<CompiledName("EventTentativeMirrored")>] EventTentativeMirrored
    | [<CompiledName("EventDeclined")>] EventDeclined
